version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - run: 
          name: auth registry with project
          command: |
              find ~/ -name .npmrc -type f | xargs rm -f
              echo -e "//npm.pkg.github.com/:_authToken=${GH_NPM_TOKEN}" > ~/project/.npmrc
      - run: npm config ls -l
      - run: npm whoami
      - run: 
          name: auth registry with global
          command: |
              npm config set registry https://npm.pkg.github.com
              npm config set //npm.pkg.github.com/:_authToken ${GH_NPM_TOKEN}
          when: on_fail 
      - run: npm config ls -l
      - run: npm whoami
      - run: npm install @nanophate-cci/package-test@1.0.0


 
